layout_spectrum: 0.006087371772892847
typography_spectrum: 0.28022864728326924
color:
  brandColors:
    - '#FCFBF6'
    - '#211310'
    - '#486082'
    - '#9CA3B5'
    - '#CB4A2B'
  brandStrength: 0.2845410922202881
  lightness: 0.5745095570708191
  saturation: 0.0018552456184815947
  rhythmicContrast: 0.5253751108969682
author:
  name: Larry Burlingame
  email: larrykathy@hotmail.com
  url: 'http://thunderbirdsalumni.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/233e9f93-825f-49dd-9c1a-d840676b1dde.png
name: ThunderbirdsAlumni
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: ThunderbirdsAlumni Forum
    url: 'http://thunderbirdsalumni.freeforums.net/'
    type: external
  - name: Photo Gallery Links
    id: 4442ced1-8977-4b4c-87af-fc133d5edef7
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5e7efddf-0ec0-4b0b-8ed3-c5888f23ff21.png
title: ThunderbirdsAlumni.com
content: []
description: Dream Of A Lifetime
purpose:
  - type: contact
    url: 'mailto:SquirrelyBurly@outlook.com'
    label: Contact me
  - type: external
    url: 'http://www.afthunderbirds.com/site/'
    label: USAF Thunderbirds Site
github: true
url: 'https://thunderbirdsalumni.com/'
