typography_spectrum: 0.03082064115230252
color:
  brandColors:
    - '#F8F9FC'
    - '#224FAA'
    - '#A62626'
    - '#3D588F'
    - '#C7CAD1'
  brandStrength: 0.8291831603128978
  lightness: 0.09360359973735222
  saturation: 0.37376909000955816
  rhythmicContrast: 0.9666886589664154
layout_spectrum: 0.35659241248152707
analytics:
  google: UA-91455698-1
  twitter: '@AFThunderbirds'
author:
  name: ThunderbirdsAlumni.com
  email: larrykathy@hotmail.com
  url: 'http://thunderbirdsalumni.com'
logo: null
name: ThunderbirdsAlumni
url: 'https://thunderbirdsalumni.com/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: 2017 Show Season
    url: 'http://afthunderbirds.com/site/show-season/'
    type: external
  - name: Thunderbirds Photo Album
    url: 'https://thunderbirdsalumni.smugmug.com/'
    type: external
  - name: Reunion 2017
    id: 75dbfe8f-40dc-438a-b2c9-47e0fdd1fcb2
    type: content
  - name: DVIDS
    url: >-
      https://www.dvidshub.net/tags/video/thunderbirds/page/1/?sub_id=150403&utm_campaign=subscriptions&utm_medium=email&utm_source=150403&utm_content=asset_link&page=1
    type: external
  - name: Alumni Forum
    url: 'http://thunderbirdsalumni.createaforum.com/'
    type: external
  - name: TBAA
    url: 'http://www.thunderbirdsalumni.org'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5e7efddf-0ec0-4b0b-8ed3-c5888f23ff21.png
title: ThunderbirdsAlumni.com
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2Ftj4-Krt71Vc%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dtj4-Krt71Vc&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2Ftj4-Krt71Vc%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'https://www.youtube.com/watch?v=tj4-Krt71Vc'
      keywords:
        - video
        - sharing
        - camera phone
        - video phone
        - free
        - upload
      related: []
      author:
        - name: afthunderbirds
          url: 'https://www.youtube.com/user/afthunderbirds'
          avatar: {}
      '@context': 'http://schema.org'
      title: Thunderbird 5 Performs Max Turn and Calypso Pass Maneuvers
      '@type': VideoObject
      app_links: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: www.youtube.com
      description: >-
        What happens when you fly a high performance fighter jet in a humid
        environment? Let Thunderbird 5 show you in his Max Turn and Calypso Pass
        maneuvers. To learn when the U.S. Air Force Thunderbirds will be soaring
        to an Air Show near you, visit www.afthunderbirds.com or follow us on
        Facebook!
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Dream Of A Lifetime
purpose:
  - type: contact
    url: 'mailto:SquirrelyBurly@outlook.com'
    label: Contact me
  - type: external
    url: 'http://www.afthunderbirds.com/site/'
    label: USAF Thunderbirds Site
github: true
