typography_spectrum: 0.813916183578791
color:
  brandColors:
    - '#F8F9FC'
    - '#224FAA'
    - '#A62626'
    - '#3D588F'
    - '#C7CAD1'
  brandStrength: 0.8226996880769729
  lightness: 0.09757354235571652
  saturation: 0.37872861419453996
  rhythmicContrast: 0.9622022134329349
github: true
layout_spectrum: 0.3246323919438268
analytics:
  google: UA-91455698-1
author:
  name: ThunderbirdsAlumni.com
  email: larrykathy@hotmail.com
  url: 'http://thunderbirdsalumni.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/233e9f93-825f-49dd-9c1a-d840676b1dde.png
name: ThunderbirdsAlumni
url: 'https://thunderbirdsalumni.com/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: 2017 Show Season
    url: 'http://afthunderbirds.com/site/show-season/'
    type: external
  - name: Thunderbirds Photo Album
    url: 'https://thunderbirdsalumni.smugmug.com/'
    type: external
  - name: Reunion News
    id: 4d6e2aee-f0b2-4ef4-a4ba-6ca8b7fb1d78
    type: content
  - name: Merchandise
    url: 'http://astore.amazon.com/gridad-20'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5e7efddf-0ec0-4b0b-8ed3-c5888f23ff21.png
title: ThunderbirdsAlumni.com
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/25e08390c69a5e3dea79e0d327101c7fb87f5801.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/25e08390c69a5e3dea79e0d327101c7fb87f5801.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: imgflo.herokuapp.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: >-
        https://imgflo.herokuapp.com/graph/2b2431f8e7ba7b0/89b25e97c9904e64e9ce267bfedaffdd/noop.jpg?input=http%3A%2F%2Fstatic.lakana.com%2Fmedia.fox13news.com%2Fphoto%2F2017%2F04%2F28%2F18076924_10155269499884246_3217013094780130224_o_1493402881855_3222472_ver1.0_640_360.jpg
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Dream Of A Lifetime
purpose:
  - type: contact
    url: 'mailto:SquirrelyBurly@outlook.com'
    label: Contact me
  - type: external
    url: 'http://www.afthunderbirds.com/site/'
    label: USAF Thunderbirds Site
