layout_spectrum: 0.006087371772892847
typography_spectrum: 0.28022864728326924
color:
  brandColors:
    - '#FCFBF6'
    - '#211310'
    - '#486082'
    - '#9CA3B5'
    - '#CB4A2B'
  brandStrength: 0.2845410922202881
  lightness: 0.5745095570708191
  saturation: 0.0018552456184815947
  rhythmicContrast: 0.5253751108969682
author:
  name: Larry Burlingame
  email: larrykathy@hotmail.com
  url: 'http://thunderbirdsalumni.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/233e9f93-825f-49dd-9c1a-d840676b1dde.png
name: ThunderbirdsAlumni
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: ThunderbirdsAlumni Forum
    url: 'http://thunderbirdsalumni.freeforums.net/'
    type: external
  - name: Photo Gallery Links
    id: 4442ced1-8977-4b4c-87af-fc133d5edef7
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5e7efddf-0ec0-4b0b-8ed3-c5888f23ff21.png
title: ThunderbirdsAlumni.com
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F3DjzwIr4k9Q%3Fstart%3D22%26feature%3Doembed%26start%3D22&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D3DjzwIr4k9Q&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F3DjzwIr4k9Q%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: afthunderbirds
          url: 'https://www.youtube.com/user/afthunderbirds'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: www.youtube.com
      keywords:
        - thunderbirds
        - afthunderbirds
        - duration
        - views
        - usaf
        - '2016'
        - air
        - flies
        - solo
        - airshow
      description: >-
        For more information about the Thunderbirds, visit:
        www.afthunderbirds.com Follow the Thunderbirds on Facebook:
        https://www.facebook.com/AFThunderbirds Follow the Thunderbirds on
        Instagram/ Twitter - @afthunderbirds
      inLanguage: en
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=3DjzwIr4k9Q&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=3DjzwIr4k9Q&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=3DjzwIr4k9Q&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=3DjzwIr4k9Q&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=3DjzwIr4k9Q&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=3DjzwIr4k9Q'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=3DjzwIr4k9Q
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=3DjzwIr4k9Q
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=3DjzwIr4k9Q&t=22s'
      title: 'Thunderbirds 2016, Year in Review'
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Dream Of A Lifetime
purpose:
  - type: contact
    url: 'mailto:SquirrelyBurly@outlook.com'
    label: Contact me
  - type: external
    url: 'http://www.afthunderbirds.com/site/'
    label: USAF Thunderbirds Site
github: true
url: 'https://thunderbirdsalumni.com/'
