typography_spectrum: 0.813916183578791
color:
  brandColors:
    - '#F8F9FC'
    - '#224FAA'
    - '#A62626'
    - '#3D588F'
    - '#C7CAD1'
  brandStrength: 0.8226996880769729
  lightness: 0.09757354235571652
  saturation: 0.37872861419453996
  rhythmicContrast: 0.9622022134329349
github: true
layout_spectrum: 0.3246323919438268
analytics:
  google: UA-91455698-1
author:
  name: ThunderbirdsAlumni.com
  email: larrykathy@hotmail.com
  url: 'http://thunderbirdsalumni.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/233e9f93-825f-49dd-9c1a-d840676b1dde.png
name: ThunderbirdsAlumni
url: 'https://thunderbirdsalumni.com/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: 2017 Show Season
    url: 'http://afthunderbirds.com/site/show-season/'
    type: external
  - name: Thunderbirds Photo Album
    url: 'https://thunderbirdsalumni.smugmug.com/'
    type: external
  - name: Reunion News
    id: 4d6e2aee-f0b2-4ef4-a4ba-6ca8b7fb1d78
    type: content
  - name: Merchandise
    url: 'http://astore.amazon.com/gridad-20'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5e7efddf-0ec0-4b0b-8ed3-c5888f23ff21.png
title: ThunderbirdsAlumni.com
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FuQCPnddBqjQ%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DuQCPnddBqjQ&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FuQCPnddBqjQ%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: MilitaryVideos.com
          url: 'https://www.youtube.com/user/militaryvideochannel'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      keywords:
        - air force
        - thunderbirds
        - usaf
        - military history
      description: >-
        History, legacy and mission of the United States Air Force Thunderbirds
        Air Demonstration Squadron. GO TO THE FRONTLINES: More videos at
        http://www.militaryvideos.com
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=uQCPnddBqjQ&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=uQCPnddBqjQ&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=uQCPnddBqjQ&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=uQCPnddBqjQ&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=uQCPnddBqjQ&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=uQCPnddBqjQ'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=uQCPnddBqjQ
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=uQCPnddBqjQ
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/uQCPnddBqjQ'
      title: 'Thunderama: History of the U.S. Air Force Thunderbirds'
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Dream Of A Lifetime
purpose:
  - type: contact
    url: 'mailto:SquirrelyBurly@outlook.com'
    label: Contact me
  - type: external
    url: 'http://www.afthunderbirds.com/site/'
    label: USAF Thunderbirds Site
