typography_spectrum: 0.813916183578791
color:
  brandColors:
    - '#F8F9FC'
    - '#224FAA'
    - '#A62626'
    - '#3D588F'
    - '#C7CAD1'
  brandStrength: 0.8226996880769729
  lightness: 0.09757354235571652
  saturation: 0.37872861419453996
  rhythmicContrast: 0.9622022134329349
layout_spectrum: 0.3246323919438268
analytics:
  google: UA-91455698-1
author:
  name: ThunderbirdsAlumni.com
  email: larrykathy@hotmail.com
  url: 'http://thunderbirdsalumni.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/233e9f93-825f-49dd-9c1a-d840676b1dde.png
name: ThunderbirdsAlumni
url: 'https://thunderbirdsalumni.com/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: 2017 Show Season
    url: 'http://afthunderbirds.com/site/show-season/'
    type: external
  - name: Thunderbirds Photo Album
    url: 'https://thunderbirdsalumni.smugmug.com/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5e7efddf-0ec0-4b0b-8ed3-c5888f23ff21.png
title: ThunderbirdsAlumni.com
content: []
description: Dream Of A Lifetime
purpose:
  - type: contact
    url: 'mailto:SquirrelyBurly@outlook.com'
    label: Contact me
  - type: external
    url: 'http://www.afthunderbirds.com/site/'
    label: USAF Thunderbirds Site
github: true
